UserSchedule/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserSchedule.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

UserSchedule/Controllers/UserManagmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserSchedule.Controllers
{
    public class UserManagmentController : Controller
    {
        [HttpGet]
        public ActionResult Read()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Update()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete()
        {
            return View();
        }
    }
}

UserSchedule/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Главная";
    ViewBag.Active = "Главная";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<h1>Главная страница</h1>
<hr />
<h3>Создана без: стандартного шаблона, пап, мам, кредитов и смс...</h3>

UserSchedule/Views/Shared/MainLayout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Html.Partial("Styles")
</head>
<body style="padding-top:65px">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">График</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <input type="hidden" id="selectedMenu" value="@ViewBag.Active" />
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Default")">Главная</a></li>
                    <li><a href="@Url.Action("Read","UserManagment")">Пользователи</a></li>
                    <li><a href="@Url.Action("Index","Schedule")">График</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted">At the bottom of the bottle...</p>
        </div>
    </footer>
    @Html.Partial("Scripts")
</body>
</html>

UserSchedule/Views/Shared/Scripts.cshtml
<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/linq.js"></script>
<script src="~/Scripts/App.js"></script>

UserSchedule/Views/Shared/Styles.cshtml
<link rel="stylesheet" href="~/Content/bootstrap.css" />
<link rel="stylesheet" href="~/Content/App.css" />

UserSchedule/Views/UserManagment/Read.cshtml
@{
    ViewBag.Title = "Управление пользователями";
    ViewBag.Active = "Пользователи";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}
<h1>Управление пользователями</h1>
<hr />
<h3>Logic...</h3>